{% set name = "ndx-pose" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ndx_pose-{{ version }}.tar.gz
  sha256: 4b356c730bda0d273b49e44576343162be26f42c292662d7358efebd252324cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    # ndx-pose sets a min version of pynwb = 2.6.0 but the conda feedstock for that
    # version of pynwb did not set a max version of hdmf,
    # so to prevent an older version of pynwb being installed to accommodate a newer
    # and incompatible version of hdmf, raise the minimum version of pynwb to the 
    # one that sets a max version of hdmf
    - pynwb >=3.1.0
    - hdmf >=3.13.0

test:
  source_files:
    - src/pynwb/tests
    - examples
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - ndx_pose
  commands:
    - pip check
    - pytest -vv

about:
  home: https://github.com/rly/ndx-pose
  summary: NWB extension to store pose estimation data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rly
